PSQL    := docker compose exec -T pg-primary psql -U postgres -d shop -v ON_ERROR_STOP=1
PGURL   := postgresql://postgres:lab@localhost:5432/shop

# Small dataset:  make setup SIZE=small
ifeq ($(SIZE),small)
  SETUP_VARS := -v n_users=20000 -v n_products=2000 -v n_orders=200000
else
  SETUP_VARS :=
endif

.DEFAULT_GOAL := help
.PHONY: help up setup bench results psql replicas shards down clean reset

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
	  | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

up: ## Start the primary node
	docker compose up -d pg-primary
	@until docker compose exec -T pg-primary pg_isready -U postgres -q; do sleep 1; done
	@echo "primary ready on localhost:5432"

setup: up ## Load schema + data (add SIZE=small for a fast run)
	$(PSQL) $(SETUP_VARS) -f /lab/00_setup.sql

bench: ## Run the benchmark suite and write RESULTS.md
	$(PSQL) -f /lab/bench/harness.sql
	$(PSQL) -f /lab/bench/benchmarks.sql
	@$(MAKE) --no-print-directory results

results: ## Regenerate RESULTS.md from the last benchmark run
	@{ \
	  echo "# Benchmark results"; echo; \
	  echo "Generated by \`make bench\`. Reproduce with the instructions in the README."; echo; \
	  echo "\`\`\`"; \
	  docker compose exec -T pg-primary psql -U postgres -d shop -tAc \
	    "SELECT version()"; \
	  docker compose exec -T pg-primary psql -U postgres -d shop -tAc \
	    "SELECT 'shared_buffers=' || setting || ' | work_mem=' || \
	     (SELECT setting FROM pg_settings WHERE name='work_mem') \
	     FROM pg_settings WHERE name='shared_buffers'"; \
	  echo "\`\`\`"; echo; \
	  echo "## Time and I/O"; echo; \
	  docker compose exec -T pg-primary psql -U postgres -d shop -tAc \
	    "SELECT bench.report()"; \
	  echo; echo "## Plan changes"; echo; \
	  docker compose exec -T pg-primary psql -U postgres -d shop -tAc \
	    "SELECT bench.plan_report()"; \
	} > RESULTS.md
	@echo "wrote RESULTS.md"

psql: ## Open an interactive session
	docker compose exec pg-primary psql -U postgres -d shop

replicas: ## Start the two streaming replicas (step 04)
	docker compose up -d pg-replica1 pg-replica2

shards: ## Start the two shard nodes (step 05, part 2)
	docker compose up -d pg-shard0 pg-shard1

down: ## Stop everything, keep the data
	docker compose stop

clean: ## Stop everything and delete the volumes
	docker compose down -v

reset: clean setup ## Wipe and rebuild from scratch
